- name: install libselinux-python
  yum: name=libselinux-python state=present

- name: install libsemanage-python
  yum: name=libsemanage-python state=present

- name: Get selinux status
  command: getenforce
  register: selinux_status

- name: set selinux state and policy
  selinux:
    policy={{ selinux_policy }}
    state={{ selinux_state }}

- name: Give a message to reboot machine on changing from disabled to enabled
  fail: msg="You will have to reboot machine to have selinux enabled. Reboot and trigger installation again. If you wish to disable selinux, set 'selinux_state' to permissive or disabled in /etc/bahmni-installer/setup.yml"
  when: selinux_status.stdout.find("Disabled") != -1

- include: enforcing_policies.yml
  when: selinux_state == 'enforcing'
