- name: Start openmrs server
  service:
    name: openmrs
    state: started
  always_run: yes
  delegate_to: "{{ groups['bahmni-emr'][0] }}"

- name: Start bahmni-reports service
  service:
    name: bahmni-reports
    state: started
  ignore_errors: true
  always_run: yes
  delegate_to: "{{ groups['bahmni-emr'][0] }}"
