- name: Fail if email is not provided
  fail: msg="Please specify email to be set to the server for setting up nagios in /etc/bahmni-installer/setup.yml"
  when: email is not defined

- include: nagios.yml
  tags: install-nagios

- include: email.yml
  tags: configure-email
