- hosts: all
  sudo: yes
  roles:
    - { role: bahmni-base }
    - { role: bahmni-user }
    - { role: selinux, selinux_state: permissive, selinux_policy: targeted }
  tags:
    - setup


- hosts: bahmni-emr-db
  sudo: yes
  roles:
    - { role: mysql }
  tags:
    - bahmni-emr-db

- hosts: bahmni-emr
  sudo: yes
  roles:
    - { role: bahmni-emr }
  tags:
    - bahmni-emr

