- name: bahmni-emr-TDD
  hosts: server
  sudo: yes
  roles:
    - bahmni-emr
    - bahmni-base
    - bahmni-erp
    - bahmni-erp-connect
    - bahmni-event-log-service

- hosts: bahmni-emr
  sudo: yes
  roles:
    - { role: httpd-maintenance, maintenance_status: start }

- hosts: all
  sudo: yes
  roles:
    - { role: selinux, selinux_state: enforcing, selinux_policy: targeted, tags: selinux }
    - { role: bahmni-base }
    - { role: bahmni-user }
    - { role: installer-config }
    - { role: bahmni-support-user, tags: support-user }
    - { role: iptables, tags: iptables }
  tags:
    - setup

- hosts: bahmni-emr-db,bahmni-emr-db-slave
  sudo: yes
  roles:
    - { role: mysql }
  tags:
    - bahmni-emr-db
    - bahmni-emr

- hosts: bahmni-emr-db
  sudo: yes
  roles:
    - { role: mysql-users }
  tags:
    - bahmni-emr-db
    - bahmni-emr

- hosts: bahmni-emr
  sudo: yes
  roles:
    - { role: httpd }
    - { role: bahmni-emr }
    - { role: bahmni-web }
    - { role: bahmni-implementer-interface }
    - { role: bahmni-backup-upload-directories, tags: backup-upload-dir }
    - { role: implementation-config, tags: config}
    - { role: bahmni-offline, when: "{{ groups['bahmni-offline'] | length }} > 0"}
  tags:
    - bahmni-emr

- hosts: bahmni-reports
  sudo: yes
  roles:
    - { role: bahmni-reports }
  tags:
    - bahmni-reports

- hosts: bahmni-lab-db,bahmni-lab-db-slave
  sudo: yes
  roles:
    - { role: postgres, postgres_user: clinlims }
  tags:
    - bahmni-lab-db
    - bahmni-lab

- hosts: bahmni-lab
  sudo: yes
  roles:
    - { role: bahmni-lab }
  tags:
    - bahmni-lab

- hosts: bahmni-emr
  sudo: yes
  roles:
    - { role: bahmni-lab-connect, when: "{{ groups['bahmni-lab'] | length }} > 0" }
  tags:
    - bahmni-lab-connect

- hosts: bahmni-erp-db:bahmni-erp-db-slave
  sudo: yes
  roles:
    - { role: postgres, postgres_user: openerp }
  tags:
    - bahmni-erp-db
    - bahmni-erp

- hosts: bahmni-erp
  sudo: yes
  roles:
    - { role: bahmni-erp }
  tags:
    - bahmni-erp

- hosts: bahmni-erp
  sudo: yes
  roles:
    - { role: bahmni-erp-connect }
  tags:
    - bahmni-erp-connect

- hosts: pacs-integration-db:pacs-integration-db-slave
  sudo: yes
  roles:
    - { role: postgres, postgres_user: pacs }
  tags:
    - pacs-integration-db
    - pacs-integration

- hosts: pacs-integration
  sudo: yes
  roles:
    - { role: pacs-integration }
  tags:
    - pacs-integration

- hosts: dcm4chee-db,dcm4chee-db-slave
  sudo: yes
  roles:
    - { role: postgres }
  tags:
    - dcm4chee-db
    - dcm4chee

- hosts: dcm4chee
  sudo: yes
  roles:
    - { role: dcm4chee }
  tags:
    - dcm4chee

- hosts: bahmni-event-log-service
  sudo: yes
  roles:
    - { role: bahmni-event-log-service }
  tags:
    - event-log

- hosts: all
  sudo: yes
  roles:
    - { role: nagios-agent, when: "{{ groups['nagios-server'] | length }} > 0" }
  tags:
    - nrpe
    - nagios

- hosts: nagios-server
  sudo: yes
  roles:
    - { role: nagios, when: "{{ groups['nagios-server'] | length }} > 0"}
  tags:
    - nagios-server
    - nagios

- hosts: bahmni-emr
  sudo: yes
  roles:
    - { role: httpd-maintenance, maintenance_status: end }
