- hosts: all
  sudo: yes
  roles:
    - { role: bahmni-base }
    - { role: bahmni-user }
    - { role: selinux, selinux_state: permissive, selinux_policy: targeted }
  tags:
    - setup

- hosts: bahmni-emr-db
  sudo: yes
  roles:
    - { role: mysql }
  tags:
    - bahmni-emr-db

- hosts: bahmni-emr
  sudo: yes
  roles:
    - { role: bahmni-emr }
    - { role: bahmni-web }
    - { role: implementation-config }
  tags:
    - bahmni-emr

- hosts: bahmni-erp
  sudo: yes
  roles:
    - { role: bahmni-erp }
  tags:
    - bahmni-erp

- hosts: bahmni-lab
  sudo: yes
  roles:
    - { role: bahmni-lab }
  tags:
    - bahmni-lab

