- hosts: bahmni-emr-db
  become: yes
  roles:
    - { role: httpd-maintenance, maintenance_status: start}
    - { role: mysql-db-backup-incr, when: backup_type == 'all' or options == 'openmrs' or options == 'all' }
    - { role: httpd-maintenance, maintenance_status: end }


- name: Backing data via pgbackrest
  hosts: postgres-backup-tool
  sudo: yes
  roles:
    - { role: httpd-maintenance, maintenance_status: start}
    - { role: pgbackrest-backup, when: backup_type == 'all' or options == 'postgres' or options == 'all'}
    - { role: httpd-maintenance, maintenance_status: end}
