- hosts: bahmni-emr-db
  become: yes
  roles:
    - { role: httpd-maintenance, maintenance_status: start}
    - { role: mysql-db-backup-incr }
    - { role: httpd-maintenance, maintenance_status: end }
  when: backup_type == all or option == openmrs or option == all

- host: postgres-backup-tool
  sudo: yes
  roles:
    - { role: httpd-maintenance, maintenance_status: start}
    - pgbackrest-backup
    - { role: httpd-maintenance, maintenance_status: end}
  when: backup_type == all or option == postgres or option == all