- name: Restoring db via pgbackrest
  hosts: postgres-backup-tool
  sudo: yes
  roles:
    - { role: httpd-maintenance, maintenance_status: start}
    - { role: pgbackrest-restore, when: restore_type == 'all' or options == 'postgres' or options == 'all'}
    - { role: httpd-maintenance, maintenance_status: end}


