- hosts: bahmni-emr-db
  become: yes
  roles:
    - { role: httpd-maintenance, maintenance_status: start}
    - { role: mysql-db-restore-incr}
    - { role: httpd-maintenance, maintenance_status: end}
