- hosts: bahmni-emr-db
  become: yes
  roles:
    - { role: mysql-db-backup-incr, when: "db == 'openmrs'" }

- hosts: bahmni-reports-db
  become: yes
  roles:
    - { role: mysql-db-backup-incr, when: "db == 'bahmni_reports'" }
