- name: Make sure old backup temporary dest file is deleted
  file: path={{item}}  state=absent
  with_items:
    - "{{backup_temp_dest_dir}}"

- name: Make sure temporary backup directory exists
  file: path={{item}} owner=root group=root mode=0755 state=directory
  with_items:
    - "{{backup_temp_dest_dir}}"

- name: Make sure backup log directory exists
  file: path={{item}} owner=root group=root mode=0755 state=directory
  with_items:
    - "{{backup_log_file_dir}}"

- name: Make sure backup log file exists
  file: path={{item}} owner=root group=root mode=0755 state=touch
  with_items:
    - "{{backup_log_file}}"

- name: copy reports from src to dest location
  shell:
         tar -czvf {{backup_temp_dest_dir}}/$(date +%Y-%m-%d_%H%M%S)-{{item.name}}.tar.gz {{item.from_path}}  2>{{backup_log_file}};
         cp {{backup_temp_dest_dir}}/$(ls -t {{backup_temp_dest_dir}} | grep {{item.name}}) {{item.to_path}} 2>{{backup_log_file}};
  async: 86400
  when: "options in item.name or options =='all'"
  with_items:
      - { from_path: "{{reports.backup_from_path}}", to_path: "{{reports.backup_to_path}}" , name: reports}

- name: copy pacs images from src to dest location
  shell:
          tar -czvf {{backup_temp_dest_dir}}/$(date +%Y-%m-%d_%H%M%S)-{{item.name}}.tar.gz {{item.from_path}}  2>{{backup_log_file}};
          cp {{backup_temp_dest_dir}}/$(ls -t {{backup_temp_dest_dir}} | grep {{item.name}}) {{item.to_path}} 2>{{backup_log_file}};
  async: 86400
  when: "options in item.name or options == 'all'"
  with_items:
      - { from_path: "{{pacs_images.backup_from_path}}", to_path: "{{pacs_images.backup_to_path}}" , name: pacs_images}

- name: copy patient images from src to dest location
  shell: tar -czvf {{backup_temp_dest_dir}}/$(date +%Y-%m-%d_%H%M%S)-{{item.name}}.tar.gz {{item.from_path}}  2>{{backup_log_file}};
         cp {{backup_temp_dest_dir}}/$(ls -t {{backup_temp_dest_dir}} | grep {{item.name}}) {{item.to_path}} 2>{{backup_log_file}};
  async: 86400
  when: "options in item.name or options == 'all'"
  with_items:
      - { from_path: "{{patient_images.backup_from_path}}", to_path: "{{patient_images.backup_to_path}}", name: patient_images}

- name: copy document images from src to dest location
  shell:
         tar -czvf {{backup_temp_dest_dir}}/$(date +%Y-%m-%d_%H%M%S)-{{item.name}}.tar.gz {{item.from_path}}  2>{{backup_log_file}};
         cp {{backup_temp_dest_dir}}/$(ls -t {{backup_temp_dest_dir}} | grep {{item.name}}) {{item.to_path}} 2>{{backup_log_file}};
  async: 86400
  when: "options in item.name or options == 'all'"
  with_items:
      - { from_path: "{{document_images.backup_from_path}}", to_path: "{{document_images.backup_to_path}}", name: document_images}

- name: copy uploaded files from src to dest location
  shell:
        tar -czvf {{backup_temp_dest_dir}}/$(date +%Y-%m-%d_%H%M%S)-{{item.name}}.tar.gz {{item.from_path}}  2>{{backup_log_file}};
        cp {{backup_temp_dest_dir}}/$(ls -t {{backup_temp_dest_dir}} | grep {{item.name}}) {{item.to_path}} 2>{{backup_log_file}};
  async: 86400
  when: "options in item.name or options == 'all'"
  with_items:
      - { from_path: "{{uploaded_files.backup_from_path}}", to_path: "{{uploaded_files.backup_to_path}}", name: uploaded_files}

- name: copy uploaded results from src to dest location
  shell:
         tar -czvf {{backup_temp_dest_dir}}/$(date +%Y-%m-%d_%H%M%S)-{{item.name}}.tar.gz {{item.from_path}}  2>{{backup_log_file}};
         cp {{backup_temp_dest_dir}}/$(ls -t {{backup_temp_dest_dir}} | grep {{item.name}}) {{item.to_path}} 2>{{backup_log_file}};
  async: 86400
  when: "options in item.name or options == 'all'"
  with_items:
      - { from_path: "{{uploaded_results.backup_from_path}}", to_path: "{{uploaded_results.backup_to_path}}", name: uploaded_results}


