- name: Install bahmni-lab from bahmni-repo
  yum: name="bahmni-lab-{{ bahmni_lab_version }}" state=present

- name: Copy bahmni-lab config
  template:
    src=bahmni-lab.conf.j2
    dest=/etc/bahmni-lab/bahmni-lab.conf
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Copy hibernate config
  template:
    src=hibernate.cfg.xml.j2
    dest=/opt/bahmni-lab/bahmni-lab/WEB-INF/classes/us/mn/state/health/lims/hibernate/hibernate.cfg.xml
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Copy log4j config
  template:
    src=log4j.xml.j2
    dest=/opt/bahmni-lab/bahmni-lab/WEB-INF/classes/
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Copy atomfeed properties
  template:
    src=atomfeed.properties.j2
    dest=/opt/bahmni-lab/bahmni-lab/WEB-INF/classes/atomfeed.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}


- name: Get IpTable rules
  shell: iptables -nL INPUT
  register: iptablesrules
 
- name: Allow bahmni-lab port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  {{ bahmni_lab_port }} -j ACCEPT -m comment --comment "BAHMNILAB"
  when: iptablesrules.stdout.find("BAHMNILAB") == -1

- name: save iptables
  command: service iptables save


- name: Start bahmni-lab and enable at boot
  service:
    name=bahmni-lab
    enabled=yes
    state=started

