---
- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: add bahmni yum repo
  template: src=bahmni.repo.j2 dest=/etc/yum.repos.d/bahmni.repo

- name: Install EPEL repo.
  yum:
    name: "epel-release"
    state: present

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp

- name: Fail if timezone is not provided
  fail: msg="Please specify timezone to be set to the server in /etc/bahmni-installer/setup.yml"
  when: timezone is not defined

- name: Set the correct timezone.
  file: src=/usr/share/zoneinfo/{{ timezone }}  dest=/etc/localtime state=link force=yes
  tags: ntp

- name: start and enable ntpd
  service: name=ntpd state=started enabled=yes
  tags: ntp

- name: install utils
  yum: name={{ item }} state=present
  with_items:
    - tree
    - htop
    - lsof
    - wget
    - unzip
    - python-pip
    - rsync
  tags: utils

