---
- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: add bahmni yum repo
  template: src=bahmni.repo.j2 dest=/etc/yum.repos.d/bahmni.repo

- name: Add exclusions of bahmni and openmrs packages for yum update if no exclusions present
  script: add_exclusions.sh
  tags: exclude

- name: Append bahmni package exclusion to existing exclusions of yum update if present
  lineinfile:
    dest=/etc/yum.conf
    state=present
    backrefs=yes
    backup=yes
    regexp='(exclude=(?!.*bahmni\*).*)'
    line='\1 bahmni*'
  tags: exclude

- name: Append openmrs package exclusion to existing exclusions of yum update if present
  lineinfile:
    dest=/etc/yum.conf
    state=present
    backrefs=yes
    backup=yes
    regexp='(exclude=(?!.*openmrs\*).*)'
    line='\1 openmrs*'
  tags: exclude

- name: Install EPEL repo.
  yum:
    name: "epel-release"
    state: present

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp
  
- name: Set the correct timezone.
  file: src=/usr/share/zoneinfo/{{ bahmni_ntp_timezone }}  dest=/etc/localtime state=link force=yes
  tags: ntp

- name: start and enable ntpd
  service: name=ntpd state=started enabled=yes
  tags: ntp

- name: install utils
  yum: name={{ item }} state=present
  with_items:
    - tree
    - htop
    - lsof
    - wget
    - unzip
    - python-pip
  tags: utils

