---
- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present

- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp
  
- name: Set the correct timezone.
  file: src=/usr/share/zoneinfo/{{ bahmni_ntp_timezone }}  dest=/etc/localtime state=link force=yes
  tags: ntp

- name: start and enable ntpd
  service: name=ntpd state=started enabled=yes
  tags: ntp

- name: install utils
  yum: name={{ item }} state=present
  with_items:
    - tree
    - htop
    - lsof
  tags: utils

- name: add bahmni yum repo
  template: src=bahmni.repo.j2 dest=/etc/yum.repos.d/bahmni.repo

- name: create /etc/bahmni-installer directory
  file: path=/etc/bahmni-installer state=directory mode=0755 owner={{ bahmni_user }} group={{ bahmni_group }}

- name: add bahmni configuration file
  template:
      src=bahmni.conf.j2
      dest=/etc/bahmni-installer/bahmni.conf
      mode=644
      owner={{ bahmni_user }}
      group={{ bahmni_group }}

