- name: Get matched IpTable rule
  shell: iptables -nL --line-numbers | grep "WEB SERVER"  -m 1 | cut -c 1-2
  register: matchedRule

- name: delete matching rule if exists
  shell: iptables -D INPUT {{ matchedRule.stdout }}
  when: matchedRule.stdout!=""

- name: Allow port 80 through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  80 -j ACCEPT -m comment --comment "WEB SERVER"

- name: save iptables
  command: service iptables save

- name: Get matched IpTable rule
  shell: iptables -nL --line-numbers | grep https  -m 1 | cut -c 1-2
  register: matchedRule

- name: delete matching rule if exists
  shell: iptables -D INPUT {{ matchedRule.stdout }}
  when: matchedRule.stdout!=""

- name: Allow port 443 through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  443 -j ACCEPT -m comment --comment "https"

- name: save iptables
  command: service iptables save

- name: Install bahmni-web from bahmni repo
  yum: name="bahmni-web-{{ bahmni_emr_version }}" state=present
