- name: Get IpTable rules
  shell: iptables -nL INPUT
  register: iptablesrules

- name: Allow port 80 through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  80 -j ACCEPT -m comment --comment "WEB SERVER"
  when: iptablesrules.stdout.find("WEB SERVER") == -1

- name: Allow port 443 through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  443 -j ACCEPT -m comment --comment "https"
  when: iptablesrules.stdout.find("https") == -1

- name: save iptables
  command: service iptables save

- name: Install bahmni-web from bahmni repo
  yum: name="bahmni-web-{{ emr_version }}" state=present

- name: Start httpd
  service: name=httpd state=restarted enabled=yes
  tags: run_bahmni_web

