- name: Make sure temporary backup directory exists
  file: path={{item}} owner=root group=root mode=0755 state=directory
  with_items:
    - "{{restore_temp_dest_dir}}"

- name: Make sure backup log directory exists
  file: path={{item}} owner=root group=root mode=0755 state=directory
  with_items:
    - "{{backup_log_file_dir}}"

- name: Make sure restore log file exists
  file: path={{item}} owner=root group=root mode=0755 state=touch
  with_items:
    - "{{restore_log_file}}"

- name: restore artifacts from dest to src location
  shell:
         tar -xzvf {{item.from_path}}/$(ls -A1 {{item.from_path}} | grep {{item.name}} | tail -1) --strip-components 2 -C {{restore_temp_dest_dir}}  2>{{restore_log_file}};
         cp -r {{restore_temp_dest_dir}}/{{item.name}} {{item.to_path}} 2>{{restore_log_file}};
  when: "item.name in options"
  with_items:
     - { from_path: "{{patient_images.restore_from_path}}", to_path: "{{patient_images.restore_to_path}}", name: patient_images}
     - { from_path: "{{document_images.backup_from_path}}", to_path: "{{document_images.backup_to_path}}", name: document_images}
     - { from_path: "{{uploaded_files.backup_from_path}}", to_path: "{{uploaded_files.backup_to_path}}", name: uploaded_files}
     - { from_path: "{{uploaded_results.backup_from_path}}", to_path: "{{uploaded_results.backup_to_path}}", name: uploaded_results}
     - { from_path: "{{pacs_images.backup_from_path}}", to_path: "{{pacs_images.backup_to_path}}" , name: pacs_images}
     - { from_path: "{{reports.backup_from_path}}", to_path: "{{reports.backup_to_path}}" , name: reports}

- name: Make sure restore temporary dest dir is deleted
  file: path={{item}}  state=absent
  with_items:
    - "{{restore_temp_dest_dir}}"


