
- name: Install dcm4chee from bahmni-repo
  yum: name="dcm4chee-{{ dcm4chee_version }}" state=latest

- name: Get IpTable rules
  shell: iptables -nL INPUT
  register: iptablesrules

- name: Allow dcm4chee port through firewall
  command: /sbin/iptables -R INPUT 1 -p tcp --dport  {{ dchm4chee_port }} -j ACCEPT -m comment --comment "DCM4CHEE"
  when: iptablesrules.stdout.find("DCM4CHEE") == -1


- name: save iptables
  command: service iptables save

- name: Start dcm4chee and enable at boot
  service:
    name=dcm4chee
    enabled=yes
    state=started




