- name: Check if dcm4chee rpm needs an update
  command: yum list installed dcm4chee
  register: installed_dcm4chee
  ignore_errors: true

- name: Uninstall dcm4chee rpm
  yum: name="dcm4chee" state=absent
  when: installed_dcm4chee.stdout.find("{{ dcm4chee_version }}") == -1

- name: Install dcm4chee from bahmni-repo
  yum: name="dcm4chee-{{ dcm4chee_version }}" state=present

- name: Get matched IpTable rule
  shell: iptables -nL --line-numbers | grep DCM4CHEE  -m 1 | cut -c 1-2
  register: matchedRule

- name: delete matching rule if exists
  shell: iptables -D INPUT {{ matchedRule.stdout }}
  when: matchedRule.stdout!=""

- name: Allow dcm4chee port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  {{ dchm4chee_port }} -j ACCEPT -m comment --comment "DCM4CHEE"

- name: save iptables
  command: service iptables save

- name: Switch off chkconfig for dcm4chee on passive
  service: name=dcm4chee state=stopped enabled=no
  when: passive is defined and passive == 'yes'

- name: Stop dcm4chee
  service:
    name=dcm4chee
    state=stopped
  when: passive is not defined or passive != 'yes'
  tags: stop_bahmni

- name: Copy oviyam2-1 config
  template:
    src=oviyam2-1-config.xml.j2
    dest=/opt/dcm4chee/etc/oviyam2-1-config.xml
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Copy dcm4chee server config
  template:
    src=server.xml.j2
    dest=/opt/dcm4chee/etc/server.xml
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Copy dcm4chee conf
  template:
    src=dcm4chee.conf.j2
    dest=/opt/dcm4chee/etc/dcm4chee.conf
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Start dcm4chee and enable at boot
  service:
    name=dcm4chee
    enabled=yes
    state=started
  when: passive is not defined or passive != 'yes'
  tags: start_bahmni




