- name: Install python-gdata
  yum: name="{{ python_gdata_rpm_location }}" state=present
  
- name: Install openerp-connect from bahmni-repo
  yum: name="bahmni-erp-connect-{{ erp_connect_version }}" state=present

- name: Install openerp from bahmni-repo
  yum: name="bahmni-erp-{{ erp_version }}" state=present

- name: Start Openerp and enable at boot
  service:
    name=openerp
    enabled=yes
    state=started

