- name: Install python-gdata
  yum: name="{{ python_gdata_rpm_location }}" state=present

- name: Install openerp from bahmni-repo
  yum: name="bahmni-erp-{{ bahmni_erp_version }}" state=present

- name: Get matched IpTable rule
  shell: iptables -nL --line-numbers | grep BAHMNIERP  -m 1 | cut -c 1-2
  register: matchedRule

- name: delete matching rule if exists
  shell: iptables -D INPUT {{ matchedRule.stdout }}
  when: matchedRule.stdout!=""

- name: Allow openmrs port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  {{ openerp_port }} -j ACCEPT -m comment --comment "BAHMNIERP"

- name: save iptables
  command: service iptables save

- name: Start Openerp and enable at boot
  service:
    name=openerp
    enabled=yes
    state=started


