- name: Install python-gdata
  yum: name="{{ python_gdata_rpm_location }}" state=present
  

- name: Install openerp from bahmni-repo
  yum: name="bahmni-erp-{{ bahmni_erp_version }}" state=present

- name: Get IpTable rules
  shell: iptables -nL INPUT
  register: iptablesrules

- name: Allow openmrs port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  {{ openerp_port }} -j ACCEPT -m comment --comment "BAHMNIERP"
  when: iptablesrules.stdout.find("BAHMNIERP") == -1

- name: save iptables
  command: service iptables save

- name: Start Openerp and enable at boot
  service:
    name=openerp
    enabled=yes
    state=started


