- name: Check if pacs-integration rpm needs an update
  command: yum list installed pacs-integration
  register: installed_pacs_integration
  ignore_errors: true

- name: Uninstall pacs-integration rpm
  yum: name="pacs-integration" state=absent
  when: installed_pacs_integration.stdout.find("{{ pacs_integration_version }}") == -1

- name: Install pacs-integration from bahmni-repo
  yum: name="pacs-integration-{{ pacs_integration_version }}" state=present

- name: Copy pacs-integration config
  template:
    src=pacs-integration.conf.j2
    dest=/opt/pacs-integration/etc/pacs-integration.conf
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Copy oviyam2-1 config
  template:
    src=oviyam2-1-config.xml.j2
    dest=/opt/pacs-integration/etc/oviyam2-1-config.xml
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Copy atomfeed properties
  template:
    src=atomfeed.properties.j2
    dest=/opt/pacs-integration/pacs-integration/WEB-INF/classes/atomfeed.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Copy application properties
  template:
    src=application.properties.j2
    dest=/opt/pacs-integration/pacs-integration/WEB-INF/classes/application.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Copy initDB shell script
  template:
    src=initDB.sh.j2
    dest=/opt/pacs-integration/pacs-integration/datasetup/initDB.sh
    mode=744
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Get matched IpTable rule
  shell: iptables -nL --line-numbers | grep BAHMNIPACS  -m 1 | cut -c 1-2
  register: matchedRule

- name: delete matching rule if exists
  shell: iptables -D INPUT {{ matchedRule.stdout }}
  when: matchedRule.stdout!=""

- name: Allow pacs-integration port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  {{ pacs_integration_port }} -j ACCEPT -m comment --comment "BAHMNIPACS"

- name: save iptables
  command: service iptables save

- name: Switch off chkconfig for pacs-integration on passive
  service: name=pacs-integration state=stopped enabled=no
  when: passive is defined and passive == 'yes'

- name: Stop pacs-integration
  service:
    name=pacs-integration
    state=stopped
  when: passive is not defined or passive != 'yes'
  tags: stop_bahmni

- name: Copy script to update localhost with remote IP in markers
  template:
      src=add_remote_ip_in_bahmni_pacs_markers.sh.j2
      dest=/opt/pacs-integration/add_remote_ip_in_bahmni_pacs_markers.sh
      mode=755

- name: Update bahmni-pacs markers with remote IP
  shell: /opt/pacs-integration/add_remote_ip_in_bahmni_pacs_markers.sh

- name: Start pacs-integration and enable at boot
  service:
    name=pacs-integration
    enabled=yes
    state=started
  when: passive is not defined or passive != 'yes'
  tags: start_bahmni