#- name: Run restore script for preparing restoratoin files.
#  script: restore_backup.sh {{ file_path }} {{restore_point}}
#  sudo: yes


- name: Restore backup
  command: rsync -arP --del /db-restore/201701200736_full/{{db_name}}/ /var/lib/mysql/{{db_name}}/
