- name: Get openmrs db file path
  stat: path={{ file_path }}
  register: mysql_dump_file_path
  failed_when: mysql_dump_file_path.stat.exists == false

- name: Create /db-restore
  file:
    path=/db-restore
    state=directory

- name: Copy database backup to the machine
  copy: src={{ file_path }}
        dest=/db-restore/openmrs_dump.sql.gz
        mode=644
        owner={{ bahmni_user }}
        group={{ bahmni_group }}

- name: Drop openmrs database
  mysql_db:
    name=openmrs
    login_user={{ mysql_root_user }}
    login_password={{ mysql_root_password }}
    state=absent

- name: Restore openmrs db
  shell: gunzip -c /db-restore/openmrs_dump.sql.gz | mysql -u{{ mysql_root_user }} -p{{ mysql_root_password }}

- name: Delete restored file
  file:
    path=/db-restore/openmrs_dump.sql.gz
    state=absent
