- name: Uninstalling implementer interface if disabled.
  yum:  name="bahmni-implementer-interface" state=absent
  when: (implementer_interface is not defined or implementer_interface != 'enabled')

- name: Installing implementer interface rpm if enabled.
  yum:  name="bahmni-implementer-interface" state=latest update_cache=yes
  when: (implementer_interface is defined and implementer_interface == 'enabled')
