- include: installer-config.yml
  when: installer_config_role_ran is not defined or installer_config_role_ran != true

- name: Creating bahmni-backrest.conf file
  sudo: yes
  file:
        path=/etc/bahmni-backrest.conf
        state=touch
        owner=root
        mode=777

- name: Creating backrest log directory
  sudo: yes
  file:
        path=/var/log/backrest
        state=directory
        mode=777

- name: Creating pgbackrest repo directory
  sudo: yes
  file:
        path=/var/lib/pgbackrest
        state=directory
        mode=777

- name: Editing bahmni-backrest.conf file
  sudo: yes
  template:
       src=bahmni-backrest.conf.j2
       dest=/etc/bahmni-backrest.conf