- name: create /etc/bahmni-installer/ directory
  file: path=/etc/bahmni-installer state=directory mode=0755 owner={{ bahmni_user }} group={{ bahmni_group }}

- name: create /etc/bahmni-installer/deployment-artifacts directory
  file: path=/etc/bahmni-installer/deployment-artifacts state=directory mode=0755 owner={{ bahmni_user }} group={{ bahmni_group }}

- name: create /etc/bahmni-installer/backup directory
  file: path=/etc/bahmni-installer/backup state=directory mode=0755 owner={{ bahmni_user }} group={{ bahmni_group }}

- name: add bahmni configuration file
  template:
      src=bahmni.conf.j2
      dest=/etc/bahmni-installer/bahmni.conf
      mode=644
      owner={{ bahmni_user }}
      group={{ bahmni_group }}

