
- name: Make sure backup log directory exists
  file: path={{item}} owner=root group=root mode=0755 state=directory
  with_items:
    - "{{backup_log_file_dir}}"

- name: Make sure expire log file exists
  file: path={{item}} owner=root group=root mode=0755 state=touch
  with_items:
    - "{{expire_log_file}}"

- name: Copy script to expire artifacts
  template:
      src=expire-artifacts.sh.j2
      dest=/opt/bahmni-installer/expire-artifacts.sh
      mode=755
      owner=bahmni
      group=bahmni
  when: "item.name in options or options == 'all'"
  with_items:
       - { path: "{{patient_images.backup_to_path}}", name: patient_images}
       - { path: "{{document_images.backup_to_path}}", name: document_images}
       - { path: "{{uploaded_files.backup_to_path}}", name: uploaded-files}
       - { path: "{{uploaded_results.backup_to_path}}", name: uploaded_results}
       - { path: "{{pacs_images.backup_to_path}}", name: pacs_images}
       - { path: "{{reports.backup_to_path}}", name: reports}

- name: expire artifacts from src location
  script: /opt/bahmni-installer/expire-artifacts.sh
  when: "item.name in options or options == 'all'"
  with_items:
      - { path: "{{document_images.backup_to_path}}", name: document_images}
      - { path: "{{uploaded_files.backup_to_path}}", name: uploaded-files}
      - { path: "{{uploaded_results.backup_to_path}}", name: uploaded_results}
      - { path: "{{pacs_images.backup_to_path}}", name: pacs_images}
      - { path: "{{reports.backup_to_path}}", name: reports}
      - { path: "{{patient_images.backup_to_path}}", name: patient_images}




