- name: add mysql 5.6 yum repo
  template:
    src=mysql.repo.j2
    dest=/etc/yum.repos.d/mysql.repo
    
- name: Install openmrs from bahmni-repo
  yum: name="bahmni-emr-{{ emr_version }}" state=present

- name: Update and grant privileges to openmrs user
  sudo: yes
  mysql_user: 
   name: "{{ openmrs_db_username }}"
   password: "{{ openmrs_db_password }}"
   login_user: root
   login_password: "{{ mysql_root_password }}"
   host: "localhost"
   priv: "openmrs.*:ALL,GRANT"

# - name: Copy openmrs conf
#  template:
#    src=openmrs.conf.j2
#    dest={{ openmrs_install_dir }}/etc/openmrs.conf
#    mode=644
#    owner={{ bahmni_user }}
#    group={{ bahmni_group }}

# - name: Copy openmrs-runtime properties
#  template:
#    src=openmrs-runtime.properties.j2
#    dest={{ openmrs_install_dir }}/etc/openmrs-runtime.properties
#    mode=644
#    owner={{ bahmni_user }}
#    group={{ bahmni_group }}


- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules

- name: Allow bdshr port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ openmrs_port }} -j ACCEPT -m comment --comment "OPENMRS"
  when: iptablesrules.stdout.find("OPENMRS") == -1

- name: save iptables
  command: service iptables save

- name: Start openmrs
  service: name=openmrs state=restarted enabled=yes
  tags: run_openmrs
