- name: Install Apache server from yum repository
  yum: name={{item}} state=present
  with_items:
   - httpd
   - mod_ssl
   - mod_wsgi

- name: Get matched IpTable rule
  shell: iptables -nL --line-numbers | grep "WEB SERVER"  -m 1 | cut -c 1-2
  register: matchedRule

- name: delete matching rule if exists
  shell: iptables -D INPUT {{ matchedRule.stdout }}
  when: matchedRule.stdout!=""

- name: Allow port 80 through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  80 -j ACCEPT -m comment --comment "WEB SERVER"

- name: save iptables
  command: service iptables save

- name: Get matched IpTable rule
  shell: iptables -nL --line-numbers | grep https  -m 1 | cut -c 1-2
  register: matchedRule

- name: delete matching rule if exists
  shell: iptables -D INPUT {{ matchedRule.stdout }}
  when: matchedRule.stdout!=""

- name: Allow port 443 through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  443 -j ACCEPT -m comment --comment "https"

- name: save iptables
  command: service iptables save

- name: Uninstall bahmni-certs rpm
  yum: name="bahmni-certs" state=absent

- name: Install bahmni-certs from bahmni-repo
  yum: name="bahmni-certs" state=present

- name: copy ssl conf file
  template:
      src=ssl.conf.j2
      dest=/etc/httpd/conf.d/ssl.conf
      mode=644
      owner={{ bahmni_user }}
      group={{ bahmni_group }}
  tags: event-log

- name: Switch off chkconfig for httpd on passive
  service: name=httpd state=stopped enabled=no
  when: passive is defined and passive == 'yes'

- name: Stop httpd
  service: name=httpd state=stopped
  tags: 
      - run_bahmni_web
      - stop_bahmni

- name: Start httpd
  service: name=httpd state=started enabled=yes
  tags:
      - run_bahmni_web
      - start_bahmni

- name: Add landing page html file
  template:
    src=index.html.j2
    dest=/var/www/html/index.html
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Create /var/www/bahmni_revisions
  file: path=/var/www/bahmni_revisions state=directory owner={{ bahmni_user }} group={{ bahmni_group }} mode=755

- name: Copy openmrs revision file
  copy:
    src=bahmni_openmrs_revision.json
    dest=/var/www/bahmni_revisions/.
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Copy openerp revision file
  copy:
    src=bahmni_openerp_revision.json
    dest=/var/www/bahmni_revisions/.
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}
  when: "{{ groups['bahmni-erp'] | length }} > 0"

- name: Copy openelis revision file
  copy:
    src=bahmni_openelis_revision.json
    dest=/var/www/bahmni_revisions/.
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}
  when: "{{ groups['bahmni-lab'] | length }} > 0"