- name: Add maintenace page to /var/www/html
  copy:
    src={{ item }}
    dest=/var/www/html/.
  with_items:
    - maintenance.html
    - maintenance.enable
    - src.jpg
    - bahmni-logo.png
  ignore_errors: true
  when: maintenance_status == 'start'

- name: Remove maintenace enable page from /var/www/html
  file:
   path=/var/www/html/maintenance.enable
   state=absent
  when: maintenance_status == 'end'