- name: Copy implementation config to /tmp
  copy:
    src=/etc/bahmni-installer/deployment-artifacts/{{ implementation_name }}_config.zip
    dest=/tmp/{{ implementation_name }}_config.zip
    mode=755
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: remove /var/www/bahmni_config
  file: path=/var/www/bahmni_config state=absent

- name: create /var/www/bahmni_config
  file: path=/var/www/bahmni_config state=directory owner={{ bahmni_user }} group={{ bahmni_group }} mode=755

- name: Extract implementation config to /var/www/implementation_config
  unarchive:
    src=/tmp/{{ implementation_name }}_config.zip
    dest=/var/www/bahmni_config copy=no
    mode=755
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Link obscalculator in openmrs application data directory
  file: src=/var/www/bahmni_config/openmrs/obscalculator  dest=/opt/openmrs/obscalculator state=link owner={{ bahmni_user }} group={{ bahmni_group }}

- name: Link order templates in openmrs application data directory
  file: src=/var/www/bahmni_config/openmrs/ordertemplates  dest=/opt/openmrs/ordertemplates state=link owner={{ bahmni_user }} group={{ bahmni_group }}

- name: Link encounter modifiers in openmrs application data directory
  file: src=/var/www/bahmni_config/openmrs/encounterModifier  dest=/opt/openmrs/encounterModifier state=link owner={{ bahmni_user}} group={{ bahmni_group }}

- name: Link patient match algorithms in openmrs application data directory
  file: src=/var/www/bahmni_config/openmrs/patientMatchingAlgorithm  dest=/opt/openmrs/patientMatchingAlgorithm state=link owner={{ bahmni_user }} group={{ bahmni_group }}

#TODO: Below 3 tasks to be removed after removing its dependencies from bahmni-core
- name: remove /opt/openmr/bahmni_config
  file: path=/opt/openmr/bahmni_config state=absent

- name: create /var/www/bahmni_config
  file: path=/opt/openmr/bahmni_config state=directory owner={{ bahmni_user }} group={{ bahmni_group }} mode=755

- name: Link entire bahmni_config in openmrs application data directory
  file: src=/var/www/bahmni_config dest=/opt/openmrs/bahmni_config state=link owner={{ bahmni_user }} group={{ bahmni_group }}

- name: Run openmrs liquibase migrations
  script: run-implementation-openmrs-liquibase.sh

- name: Run openelis liquibase migrations
  script: run-implementation-openelis-liquibase.sh
  when: "{{ groups['bahmni-lab'] | default([]) | length }} > 0"

- name: Run openerp liquibase migrations
  script: run-implementation-openelis-liquibase.sh
  when: "{{ groups['bahmni-erp'] | default([]) | length }} > 0"
