- name: Editing pgbackrest.conf file
  sudo: yes
  template:
      src=pgbackrest.conf.j2
      dest=/etc/pgbackrest.conf

- name: Stop PostgreSQL
  service:
    name=postgresql-{{ postgres_version }}
    state=stopped
  ignore_errors: true

- name: Performing delta restore
  sudo: yes
  shell: sudo -u postgres pgbackrest --stanza=demo --delta --log-level-console=detail restore 2>>{{ logfile }}
  when: strategy == "incr"

- name: Performing full restore
  sudo: yes
  shell: sudo -u postgres pgbackrest --stanza=demo --log-level-console=detail restore 2>>{{ logfile }}
  when: strategy == "full"

- name: Performing PITR restore 
  sudo: yes 
  script: pitr.sh {{postgres.path}}  {{ restore_point }} {{ logfile }} 
  when: strategy == "pitr"

- name: Start PostgreSQL
  service:
    name=postgresql-{{ postgres_version }}
    state=running
  ignore_errors: true
